#!/bin/sh
# when running the hook, cwd is the top level of working tree

cd "$(git rev-parse --show-toplevel)"
script=tools/git-store-meta/git-store-meta.pl
[ ! -x "$script" ] && script='git-store-meta.pl'

sha_old=$1
sha_new=$2
change_br=$3

# apply metadata only when HEAD is changed
if [ ${sha_new} != ${sha_old} ]; then
    "$script" --apply
fi
