#!/bin/sh
# when running the hook, cwd is the top level of working tree

cd "$(git rev-parse --show-toplevel)"
script=tools/git-store-meta/git-store-meta.pl
[ ! -x "$script" ] && script='git-store-meta.pl'

# update (or store as fallback) the cache file if it exists
if [ -f '.git_store_meta' ]; then
    "$script" --update ||
    "$script" --store ||
    exit 1

    # remember to add the updated cache file
    git add '.git_store_meta'
fi
