.ig
Copyright (C) 2021 Charles Atkinson

Permission is granted to make and distribute verbatim copies of this
manual provided the copyright notice and this permission notice are
preserved on all copies.

Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the
entire resulting derived work is distributed under the terms of a
permission notice identical to this one.

Permission is granted to copy and distribute translations of this
manual into another language, under the above conditions for modified
versions, except that this permission notice may be included in
translations approved by the Free Software Foundation instead of in
the original English.
..
.\" No adjustment (ragged right)
.na
.TH postgres_bu 8 "11 Nov 2022" "Auroville" "Version 3.2.7"
.SH NAME
postgres_bu \- backup PostgreSQL databases using bung's pg_dump and pg_dumpall wrapper
.SH SYNOPSIS
\fbpostgres_bu \fB-c\~\fIconf \fR[\fB-C\fR] \fR[\fB-d\fR] \fR[\fB-h\fR] \fR[\fB-l\~\fIlog\fR] \fR[\fB-o\~\fIorg\fR] \fR[\fB-p\fR] \fR[\fB-s\fR] \fR[\fB-v\fR] \fR[\fB-w\fR]
.SH DESCRIPTION
postgres_bu runs pg_dump and pg_dumpall
.SH OPTIONS
.TP
Common options
.RS
.nh
postgres_bu uses only options described in bung-common(5).
.RE
.
.SH ENVIRONMENT
Environment variables are described in bung-common (5).
.SH FILES
Default directories are described in bung-common (5).
.SH EXAMPLES
-
.SH AUTHOR
Charles Atkinson bung@charlesmatkinson.org
.SH SEE ALSO
\fBbung-common\fR(5\~and\~8),
\fBpostgres_bu\fR(5),
\fBsuper_bu\fR(5\~and\~8),
.br
The bung user guide,
normally installed in /usr/share/bung/doc
