.ig
Copyright (C) 2021 Charles Atkinson

Permission is granted to make and distribute verbatim copies of this
manual provided the copyright notice and this permission notice are
preserved on all copies.

Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the
entire resulting derived work is distributed under the terms of a
permission notice identical to this one.

Permission is granted to copy and distribute translations of this
manual into another language, under the above conditions for modified
versions, except that this permission notice may be included in
translations approved by the Free Software Foundation instead of in
the original English.
..
.\" No adjustment (ragged right)
.na
.TH check_hotplug_usage 5 "11 Nov 2022" "Auroville" "Version 3.2.7"
.SH NAME
check_hotplug_usage - configuration for bung's check_hotplug_usage script
.SH SYNOPSIS
.HP
\fBCheck hotplug usage\~=\~Organisation=\fIorganisation_name \fR[[\fBEmail=\fIemail_address\fR]\~...] \fR[\fBMaxBackupAge=\fIdays\fR] \fR[\fBMaxDeviceChangeDays=\fIdays\fR]
.HP
\fBEmail for report\fB\~=\~\fI... 
.HP
\fBLog retention\fB\~=\~\fI... 
.HP
\fBOrganisation name\fB\~=\~\fI... 
.HP
\fBPre-hook\fB\~=\~\fI... 
.HP
\fBPost-hook\fB\~=\~\fI...
.HP
\fBShutdown\fB\~=\~\fI... 
.HP
.SH DESCRIPTION
This page describes the keywords specific to check_hotplug_usage
.P
The \fBbung-common\fR (5) man page describes
the configuration file format
and the common keywords ellipsised in the \fBSYNOPSIS\fR above
.SH OPTIONS (keywords)
.TP
Check hotplug usage
.RS
.HP
.nh
\fBCheck hotplug usage\~=\~Organisation=\fIorganisation_name
\fR[[\fBEmail=\fIemail_address\fR] ...]
\fR[\fBMaxBackupAge=\fIdays\fR]
\fR[\fBMaxDeviceChangeDays=\fIdays\fR]
.P
Required
.P
\fBorganisation_name\fR sets the organisation name
used in emails
and in the name of the hotplug device backup history file,
/var/log/bung/hotplug/\fIorganisation_name
.P
\fBEmail\fR sets an email address to send notification emails to
.br
\~\~\~\~Default: root
.P
\fBMaxBackupAge\fR sets the the maximum number of days allowed since the
organisation's last backup before a mail is sent
.br
\~\~\~\~Default: 3 days
.P
\fBMaxDeviceChangeDays\fR sets the the maximum number of days allowed since the
the hotplug storage device was changed before a mail is sent
.br
\~\~\~\~Default: 3 days
.RE
.
.SH ENVIRONMENT
Environment variables are described in bung-common (5).
.SH FILES
Default log: /var/log/bung/hotplug/\fIorganisation_name\fR
.br
Default directories are described in bung-common (5)
.SH EXAMPLES
Example check_hotplug_usage
normally installed in /usr/share/bung/doc/examples
.SH AUTHOR
Charles Atkinson bung@charlesmatkinson.org
.SH SEE ALSO
\fBbung-common\fR(5 and 8),
\fBcheck_hotplug_usage\fR(8)
.br
The bung user guide,
normally installed in /usr/share/bung/doc
