.ig
Copyright (C) 2021 Charles Atkinson

Permission is granted to make and distribute verbatim copies of this
manual provided the copyright notice and this permission notice are
preserved on all copies.

Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the
entire resulting derived work is distributed under the terms of a
permission notice identical to this one.

Permission is granted to copy and distribute translations of this
manual into another language, under the above conditions for modified
versions, except that this permission notice may be included in
translations approved by the Free Software Foundation instead of in
the original English.
..
.\" No adjustment (ragged right)
.na
.TH super_bu 5 "17 Mar 2022" "Auroville" "Version 3.2.2"
.SH NAME
super_bu \- configuration for bung's backup job supervisor script
.SH SYNOPSIS
.HP
\fBEmail for report\fB\~=\~\fI... 
.HP
\fBLog retention\fB\~=\~\fI... 
.HP
\fBMount\fB\~=\~\fI... 
.HP
\fBOrganisation name\fB\~=\~\fI... 
.HP
\fBPre-hook\fB\~=\~\fI... 
.HP
\fBPost-hook\fB\~=\~\fI...
.HP
\fBShutdown\fB\~=\~\fI... 
.HP
\fBSnapshot\fB\~=\~\fI... 
.HP
\fBSubsidiary script\fB\~=\~\fI... 
.HP
.SH DESCRIPTION
This page shows the common keywords valid for super_bu
.P
The \fBbung-common\fR (5) man page describes
the configuration file format
and the common keywords ellipsised in the \fBSYNOPSIS\fR above
.SH OPTIONS (keywords)
-
.RE
.
.SH ENVIRONMENT
Environment variables are described in bung-common (5).
.SH FILES
Default directories are described in bung-common (5).
.SH EXAMPLES
Example super_bu configuration files are
normally installed in /usr/share/bung/doc/examples
.SH AUTHOR
Charles Atkinson bung@charlesmatkinson.org
.SH SEE ALSO
\fBbung-common\fR(5 and 8),
\fBsuper_bu\fR(8)
.br
The bung user guide,
normally installed in /usr/share/bung/doc
