.ig
Copyright (C) 2021 Charles Atkinson

Permission is granted to make and distribute verbatim copies of this
manual provided the copyright notice and this permission notice are
preserved on all copies.

Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the
entire resulting derived work is distributed under the terms of a
permission notice identical to this one.

Permission is granted to copy and distribute translations of this
manual into another language, under the above conditions for modified
versions, except that this permission notice may be included in
translations approved by the Free Software Foundation instead of in
the original English.
..
.\" No adjustment (ragged right)
.na
.TH templated_bu 5 "11 Nov 2022" "Auroville" "Version 3.2.7"
.SH NAME
templated_bu \- configuration for bung's templated backup script
.SH SYNOPSIS
.HP
\fBEmail for report\fB\~=\~\fI... 
.HP
\fBLog retention\fB\~=\~\fI... 
.HP
\fBMount\fB\~=\~\fI... 
.HP
\fBOrganisation name\fB\~=\~\fI... 
.HP
\fBPre-hook\fB\~=\~\fI... 
.HP
\fBPost-hook\fB\~=\~\fI...
.HP
\fBShutdown\fB\~=\~\fI... 
.HP
\fBSnapshot\fB\~=\~\fI...
.HP
\fBtemplated\~= \fBtemplate=\fIfile\fR
.br
\fR[\fBhostname=\fIFQDN\fR] [\fBidentity_file=\fIfile\fR] [\fBpassword=\fIpassword\fR] [\fBusername=\fIname\fR]
.br
\fR[\fBdevice_type=\fIdevice type\fR]
.br
\fR[\fBdest_dir=\fIdir\fR] [\fBdest_dir_usage_warning=\fI%\fR] [\fBretention=\fIdays\fR]
.br
\fR[\fBgit_root=\fIdir\fR]
.br
\fR[\fBtftp_root=\fIdir\fR] [\fBtftp_server=\fIFQDN or IP address\fR]
.br
\fR[\fBtimeout=\fIduration\fR]
.HP
.SH DESCRIPTION
This page describes the keywords specific to templated_bu
.P
The \fBbung-common\fR (5) man page describes
the configuration file format
and the common keywords not detailed in the \fBSYNOPSIS\fR above
.SH OPTIONS (keywords)
.TP
templated
.RS
.HP
.nh
\fBtemplated\~= \fBtemplate=\fIfile\fR
.br
\fR[\fBhostname=\fIFQDN\fR] [\fBidentity_file=\fIfile\fR] [\fBpassword=\fIpassword\fR] [\fBusername=\fIname\fR]
.br
\fR[\fBdevice_type=\fIdevice type\fR]
.br
\fR[\fBdest_dir=\fIdir\fR] [\fBdest_dir_usage_warning=\fI%\fR] [\fBretention=\fIdays\fR]
.br
\fR[\fBgit_root=\fIdir\fR]
.br
\fR[\fBtftp_root=\fIdir\fR] [\fBtftp_server=\fIFQDN or IP address\fR]
.br
\fR[\fBtimeout=\fIduration\fR]
.P
Required
.P
\fBtemplate\fR is the file containing the commands to be executed after substitution.
.br
The format of the template file is described in the template_file man page
.P
\fBhostname\fR and associated subkeywords
set token values which may be used in the template, normally for authentication.
.P
\fBdevice_type\fR
sets a token value which may be used in the template, normally to allow a single template to be used with multiple device types.
.P
\fBdest_dir\fR
sets a token value which may be used in the template. 
.br
\fBtemplated_bu\fR treats \fBdest_dir\fR as a directory in which files are created by the template.
.P
\fBdest_dir_usage_warning\fR is the % destination file system usage that will trigger a warning
after the backup is finished.
.br
Use dest_dir_usage_warning=0 to disable.
.br
Default: 80
.P
\fBretention\fR specifies the number of days that files are kept in dest_dir.
.br
Default: 28
.P
\fBtftp_root\fR and \fBtftp_server\fR
set token values which may be used in the template, normally to specify a TFTP server and directory.
.P
\fBgit_root\fR
sets a token value which may be used in the template.
\fBtemplated_bu\fR treats \fBgit_root\fR
as the root directory of a git tree.
When git_root is used, after the template has been run, \fBtemplated_bu\fR runs git add, commit and push commands in git_root.
.P
\fBtimeout\fR specifies the default time allowed for templated commands 
before exiting with an error.
.br
\fIduration\fR is a floating point number with an optional suffix:
.br
\fBs\fR for seconds (default)
.br
\fBm\fR for  minutes
.br
\fBh\fR for hours
.br
\fBd\fR for days
.br
Default: 10 (allow the templated commands 10 seconds each to run)
.RE
.SH ENVIRONMENT
Environment variables are described in bung-common (5).
.SH FILES
Default directories are described in bung-common (5).
.SH EXAMPLES
Example templated_bu configuration files are
normally installed in /usr/share/doc/bung/examples/script.conf/
.SH AUTHOR
Charles Atkinson bung@charlesmatkinson.org
.SH SEE ALSO
\fBbung-common\fR(5 and 8),
\fBtemplated_bu\fR(8)
.br
The bung user guide,
normally installed in /usr/share/doc/bung/
